### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by valerauko** [lessonly/scim_rails#6]
Thanks for the gem!

Is there any particular reason why it's version locked to Rails 5.0? If not, it'd be great if the dependency could be eased for use with 5.2.

If there is some issue that prevents that, I'd be more than happy to help fix it.

**Comment by unixmonkey** [comment]
I don't think there's anything that would prevent this from working on other 5.x Rails versions, other than the dependency constraint.

Would it be possible for you to test it in your own application to make sure?
